---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Add Erlang Key
  apt_key:
    url: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/gpg.E495BB49CC4BBE5B.key
    state: present

- name: Add Erlang Apt Repo
  apt_repository:
    repo: deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ ansible_distribution_release }} main
    filename: erlang
    state: present

- name: Add RabbitMQ Key
  apt_key:
    url: https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/gpg.9F4587F226208342.key
    state: present

- name: Add RabbitMQ Apt Repo
  apt_repository:
    repo: deb https://dl.cloudsmith.io/public/rabbitmq/rabbitmq-server/deb/ubuntu {{ ansible_distribution_release }} main
    filename: rabbitmq
    state: present

- name: Install RabbitMQ
  apt:
    name: rabbitmq-server=3.11.4-1
    state: present

- name: Hold RabbitMQ
  dpkg_selections:
    name: rabbitmq-server
    selection: hold

- name: Add in Certs
  copy:
    src: certificates/{{ item }}
    dest: /etc/rabbitmq/{{ item }}
    owner: rabbitmq
    group: rabbitmq
    mode: '0600'
  with_items:
    - cert.pem
    - ca-bundle.pem
    - key.pem

- name: Overwrite Content of Erlang Cookie
  copy:
    dest: /var/lib/rabbitmq/.erlang.cookie
    content: VNQMAWCGVEEOZPKIYFPU
    owner: rabbitmq
    group: rabbitmq
    mode: '0400'
  notify: rabbitmq-server

- name: Copy Enabled Plugins and RabbitMQ Conf
  copy:
    src: '{{ item }}'
    dest: /etc/rabbitmq/{{ item }}
    owner: rabbitmq
    group: rabbitmq
    mode: '0640'
  with_items:
    - enabled_plugins
    - rabbitmq.conf
  notify: rabbitmq-server
