---
- name: Update and Upgrade Apt Packages
  become: true
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Add Core Packages
  apt:
    pkg:
      - clamav
      - clamav-daemon

- name: Check if Disabled Filesystems File Exists
  stat:
    path: /etc/modprobe.d/disabled_filesystems.conf
  register: disabled_file

- name: Create Disabled Filesystems File
  file:
    path: /etc/modprobe.d/disabled_filesystems.conf
    state: touch
    owner: root
    group: root
    mode: '0644'
  when: disabled_file.stat.exists == false

- name: Check if Dev Sec File Exists
  stat:
    path: /etc/modprobe.d/dev-sec.conf
  register: dev_sec_file

- name: Create Dev Sec File
  file:
    path: /etc/modprobe.d/dev-sec.conf
    state: touch
    owner: root
    group: root
    mode: '0644'
  when: dev_sec_file.stat.exists == false

- name: Add Lnes to Dev Sec File
  lineinfile:
    dest: /etc/modprobe.d/dev-sec.conf
    line: install {{ item }} /bin/true
  with_items:
    - cramfs
    - freevxfs
    - jffs2
    - hfs
    - hfsplus
    - squashfs
    - udf
    - vfat

- name: Check if Mount Line is Present
  lineinfile:
    path: /etc/fstab
    regexp: ^tmpfs /dev/shm
    state: absent
  check_mode: true
  changed_when: false
  register: mountline

- block:
    - name: Add Mount Line to fstab
      lineinfile:
        dest: /etc/fstab
        line: tmpfs /dev/shm tmpfs nodev,nosuid,noexec 0 0
        state: present

    - name: Remount dev-shm
      mount:
        path: /dev/shm
        state: mounted
        opts: remount,nodev,nosuid,noexec
        fstype: tmpfs
        src: tmpfs

  when: not mountline.found

- name: Get the List of Services
  service_facts:

- name: Disable Service
  service:
    name: autofs
    enabled: false
  when: "'autofs.service' in services"

- name: Add Hard Limit to File
  lineinfile:
    dest: /etc/security/limits.conf
    line: '* hard core 0'

- name: Add fs Line to sysctl
  lineinfile:
    dest: /etc/sysctl.conf
    line: '{{ item }}'
  with_items:
    - fs.suid_dumpable = 0
    - kernel.sysrq = 0
    - kernel.randomize_va_space = 2

- name: Set fs.dumapable to 0
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
  with_dict: '{{ sysctl_config }}'

- name: Check if Prelink Exits
  stat:
    path: /usr/bink/prelink
  register: prelink

- name: Run Prelink
  command: prelink -ua
  when: prelink.stat.exists == true

- name: Remove Prelink
  apt:
    name: prelink
    state: absent

- name: Delete motd Files
  file:
    path: /etc/update-motd.d/{{ item }}
    state: absent
  with_items:
    - 10-help-text
    - 51-cloudguest
    - 90-updates-available
    - 91-release-upgrade

- name: Create Disclaimer File
  copy:
    dest: /etc/update-motd.d/11-disclaimer
    content: |
      #!/bin/bash
      echo 'Your activity is logged and recorded for audit purposes.'
    owner: root
    group: root
    mode: '0755'

- name: Check if motd File Exists
  stat:
    path: /etc/motd
  register: motd

- name: Create motd File
  file:
    path: /etc/motd
    state: touch
    owner: root
    group: root
    mode: '0644'
  when: motd.stat.exists == false

- name: Create Issue Files
  copy:
    dest: /etc/{{ item }}
    content: Authorized uses only. All activity may be monitored and reported
    owner: root
    group: root
    mode: '0644'
  with_items:
    - issue
    - issue.net

- name: Delete xinetd Conf
  file:
    path: /etc/xinetd.conf
    state: absent

- name: Delete xinetd Dir
  file:
    path: /etc/xinetd.d
    state: absent

- name: Remove Prelink
  apt:
    pkg:
      - openbsd-inetd
      - xserver-xorg
    state: absent

- name: Disable Services
  service:
    name: '{{ item }}'
    enabled: false
  when: item in services
  with_items:
    - avahi-daemon
    - cups
    - isc-dhcp-server
    - isc-dhcp-server6
    - slapd
    - nfs-server
    - bind9
    - vsftpd
    - apache2
    - dovecot
    - smbd
    - squid
    - snmpd
    - postfix
    - rsync
    - nis

- name: Mask rpcbind
  systemd:
    name: rpcbind
    masked: true

- name: Remove Packages
  apt:
    pkg:
      - nis
      - rsh-client
      - rsh-redone-client
      - talk
      - telnet
      - ldap-utils
      - auditd
    state: absent

- name: Check if Disabled Protocols File Exists
  stat:
    path: /etc/modprobe.d/disabled_protocols.conf
  register: disabled_protocols

- name: Create Disabled Protocols File
  file:
    path: /etc/modprobe.d/disabled_protocols.conf
    state: touch
    owner: root
    group: root
    mode: '0644'
  when: disabled_protocols.stat.exists == false

- name: Add Lines to Disabled Protocols File
  lineinfile:
    dest: /etc/modprobe.d/disabled_protocols.conf
    line: install {{ item }} /bin/true
  with_items:
    - dccp
    - sctp
    - rds
    - tipc

- name: Enable Auditd on Boot
  lineinfile:
    path: /etc/default/grub
    regexp: ^GRUB_CMDLINE_LINUX=
    line: GRUB_CMDLINE_LINUX="audit=1"
  register: grub

- name: Update Grub
  command: update-grub
  when: grub.changed

- name: Enable rsyslog
  service:
    name: rsyslog
    enabled: true

- name: Add FileCreateMode in rsyslog
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: ^$FileCreateMode
    line: $FileCreateMode 0640"

- name: Enable Cron Service
  service:
    name: cron
    enabled: true

- name: Change Crontab Mode
  file:
    path: /etc/crontab
    mode: '0600'

- name: Change Cron Dir Mode
  file:
    path: /etc/cron.{{ item }}
    state: directory
    mode: '0700'
  with_items:
    - hourly
    - daily
    - weekly
    - monthly
    - d

- name: Delete .deny Files
  file:
    path: /etc/{{ item }}.deny
    state: absent
  with_items:
    - cron
    - at

- name: Check if .allow Files Exists
  stat:
    path: /etc/cron.allow
  register: allow

- name: Create .allow Files
  file:
    path: /etc/{{ item }}.allow
    owner: root
    group: root
    state: touch
    mode: '0600'
  with_items:
    - cron
    - at
  when: allow.stat.exists == False

- name: Prevent Access to su
  lineinfile:
    dest: /etc/pam.d/su
    line: auth required pam_wheel.so

- name: Change Mode of Passwd and Group Files
  file:
    path: /etc/{{ item.name }}
    mode: '{{ item.mode }}'
  with_items:
    - {name: passwd, mode: '0644'}
    - {name: passwd-, mode: '0644'}
    - {name: group, mode: '0644'}
    - {name: group-, mode: '0644'}
    - {name: shadow, mode: '0640'}
    - {name: shadow-, mode: '0640'}
    - {name: gshadow, mode: '0640'}
    - {name: gshadow-, mode: '0640'}

# - include_tasks: inspec.yaml
