---
wireguard_server_private_key: CMQM0K7i93/YPse0jdrjo4mGiZAqAYC3Yg2junq6yUw=
wireguard_server_public_key: Dqrm683wIfOJloXxSb9KjOx0e0+w6pQreuoiodG/n2s=
wireguard_server_fqdn: wireguard.uksouth.bink.sh
wireguard_server_port: 51820
wireguard_exporter_version: 1.0.0
wireguard_exporter_checksum: 85db6cbc6a44b02247cebcd8d0f0fda4402be8516cb4ddb1c86690259af320c1

wireguard_users: [
  {
    name: 'ajones@bink.com',
    ip: '10.10.10.2',
    private: '+HYLTaPWO1UZltHL2b1Fd3a4K0sb4iuX1FOaVh4c908=',
    public: 'eXN7OhEWHhRK3pFHEZ6sxJXQzO2d0AaDkAD7bSh0NhI=',
  },
  {
    name: 'abhakta@bink.com',
    ip: '10.10.10.3',
    private: 'CO7gJMh8ljyXCDAFZZTcCxtPS19U1SSeZGaT1U1dA18=',
    public: 'DSqlE25vmuAAodeaLvTc1/8ju/PsYH2crHjzd0Yo+Q4=',
  },
  {
    name: 'ah@bink.com',
    ip: '10.10.10.4',
    private: 'MBz1NYQlHmkKI3Pt/LY3nopxk7qpoVnOWc9Soetiblw=',
    public: 'paTfZLvHjv4NDSCjPuXA35KwtyVS73AJe20yNOnjkn4=',
  },
  {
    name: 'akhan@bink.com',
    ip: '10.10.10.5',
    private: 'ELIApXkrL71bs1gym8maFDpb1dOZ5lph+6goWIjLiEg=',
    public: 'bXMsy2PInxj7pPiWfpYJL7s+81fTt/C1d+RvayzRcw4=',
  },
  {
    name: 'bvas@bink.com',
    ip: '10.10.10.6',
    private: 'QBEu/ptV/y7cQJykqDrrhQOoBvr/FuR8N28KRp5H4HM=',
    public: '2tlROoW+rZatNoPi9npSmbJXqDqMMS0BM3o88PrfEh8=',
  },
  {
    name: 'bking@bink.com',
    ip: '10.10.10.7',
    private: 'OPqZoCe6ETYynfk6DT64o9IvFyUZSNVRaY8ygMy8Zkk=',
    public: '9h69nGOgql35qdW4ys1jnvFVWXyHAhf5KsoEBUjC/DQ=',
  },
  {
    name: 'bmamidisetti@bink.com',
    ip: '10.10.10.8',
    private: 'mMffa4NP1wra4XCFIC1NTxAcVKEUy0qG3Ng25/hEJ3Q=',
    public: 'I02CXcuBuchxs6HIGJepoANi4aS127xPU2y2uzeYRWg=',
  },
  {
    name: 'cg@bink.com',
    ip: '10.10.10.9',
    private: '6HNrVNzOFPRNzaSAwLWAW/Gh2XVqlzQ2SmwgK+4FzVY=',
    public: '52Kl1yX8atbD2p1ZUy0cIJfXX7N4VTv++PnFBN4J93I=',
  },
  {
    name: 'cl@bink.com',
    ip: '10.10.10.10',
    private: 'OAX0965Z24GdSUA1K1bHr1BDTCMWA1NcSW+yvbR/w1g=',
    public: '2IvxkWdJXtmN/XLK77YSOwXtjsw6nWJ3M3eNOz/zx1k=',
  },
  {
    name: 'cpressland@bink.com',
    ip: '10.10.10.11',
    private: 'cCqbMW0cOiQdcvqIXXd+wrTZEsliUdEKazzIbri4W30=',
    public: 'kUvFlCb+gdUkMit36k9em0bKEjfGl6xfqOzqc8DIdVQ=',
  },
  {
    name: 'cprior@bink.com',
    ip: '10.10.10.12',
    private: '2CkJebeCm2+p7ncmP70whh8g8zoBEv7aL2+1xoBQWU4=',
    public: 'Tn+3Q5NPS29qCMHXHEjuglAkY7vmVHpvrl9nUxIFsys=',
  },
  {
    name: 'dhodgson@bink.com',
    ip: '10.10.10.13',
    private: '0M5p1rVzsDcGWywE2w0jqnxGs3dJtYPeiVq2hNmcWmU=',
    public: 'ABcu9ps+GiKmICnLFQphz/r8x2Ye3TvBZcJa1L9qT1o=',
  },
  {
    name: 'ehankombo@bink.com',
    ip: '10.10.10.15',
    private: 'qIXr0TLueJA9byccv4QmymV4P8rU0mDoqqse2xB7Xmo=',
    public: '55J/6nN4t7hwXfwMO5wV2rojKRr/DfJI8wwxHtm9w00=',
  },
  {
    name: 'fmilani@bink.com',
    ip: '10.10.10.16',
    private: 'QPf7MDxeVqHDIjP76Nfa+ETXbaqQJummGjh3W/RHoF4=',
    public: 'tH1jsc+8NlK8hM0pbKN+sfufy3TD/d91v6KP5bCuDzs=',
  },
  {
    name: 'gs@bink.com',
    ip: '10.10.10.17',
    private: 'WNOSgZAEuUdD14C/oMr5eipw0O/bp5oK82/T5ctqlF0=',
    public: 'AqIeafzwk9EW6pgdAul61fweG6aubUVV6uBjVyU5v0w=',
  },
  {
    name: 'jrostron@bink.com',
    ip: '10.10.10.19',
    private: 'qBVCQJ92g2wILBr/4o1GMhh6DosmANvThMzYFWw9sH8=',
    public: '69q9+mPwNvXZ1eIMJ2Qhv8zUoYQ2TZES5v0hEE0dn1Y=',
  },
  {
    name: 'kaziz@bink.com',
    ip: '10.10.10.22',
    private: 'eBxYvH8SfQIu7kKrmQxXtIvX/W+3oXb12lCmOKu/R3w=',
    public: 'Z7DXE4IUWu7D/wpMmudd4M3yfzdiLJse0BuqTg9vAXc=',
  },
  {
    name: 'mswarbrick@bink.com',
    ip: '10.10.10.24',
    private: 'qHAn/8NB3qfbGLOAoH5HMZdaA/YGPNdwVLbdo3l/sUs=',
    public: 'fXJXXoqxraclg/EWOaCqcNq3EuLU+3nVRt1CngruNFo=',
  },
  {
    name: 'mmarsh@bink.com',
    ip: '10.10.10.25',
    private: 'IBx09azyMVU2mM23QS1xHaWlqVkpF2FG6UlqgTKaOmg=',
    public: 'VctqXpH1EYaHthZ2tBxEk7PQ97m0HFsQV+ThOo4yxyY=',
  },
  {
    name: 'mwoodhams@bink.com',
    ip: '10.10.10.26',
    private: 'ECPzjYA7XLRbwyrD+tWEv+ZE+IiWPnbta/YHJQjd3nY=',
    public: 'jr+iTfrkcQrLHdj4xuyOVuc6llx3Q1JUXkBQZbktwHM=',
  },
  {
    name: 'mmorar@bink.com',
    ip: '10.10.10.27',
    private: 'IHcFNwF/dpS3dIn3WHBxIAyLZYi7vzhhWVRF1jiahEo=',
    public: '/SoTqw0uiqy+SRZ63/LTboGlBX0YtdZaKqMC8Uxix2w=',
  },
  {
    name: 'ml@bink.com',
    ip: '10.10.10.28',
    private: '2HZGFBrQ5dox8VbM/iCoM5OOnum/L1qZcOecscxzV1Y=',
    public: '5xfxxr8N2bEG7scG274F+iOir7c0lseEMEMsjCF0JFM=',
  },
  {
    name: 'nodera@bink.com',
    ip: '10.10.10.29',
    private: 'kDFHsW5yTQXVjYOgfgAY1Cvq+rfEkjwCR2vwa4swNkU=',
    public: 'lB+XXsvonUj29nNy5fvFR9HEWM75eiIrFCfS8HnR4EE=',
  },
  {
    name: 'pb@bink.com',
    ip: '10.10.10.32',
    private: 'EF8zJVfyuTp/Tke3TOqBfAhKs1k71iZsyxBL6qdP63I=',
    public: 'g6eIz5TD4acLA9Exew3ECU2EMlx396NrV3WdQTFxPHw=',
  },
  {
    name: 'skotha@bink.com',
    ip: '10.10.10.35',
    private: 'IG9OdfsJGtptdAycX7R1gtWAu0INKq+yWp+BaSu7k04=',
    public: 'j0ngtj/n/qzAW7Q9sfriCa1OHaoHme6mZeR1Jt1wnBE=',
  },
  {
    name: 'sperrygrove@bink.com',
    ip: '10.10.10.36',
    private: 'YJKb8w23aK8sM9HQcKPUneZd8Lpvde+/cDjnOOiMk0E=',
    public: 'TgEWMmtHsEbCmkG1FD4D1pccJjAAPHKGbZGDJDJCI0I=',
  },
  {
    name: 'sking@bink.com',
    ip: '10.10.10.37',
    private: 'WJkg0Y9V1dt4AgP+4WmjUavW6U5P2NG9XqEJ6LuL73Y=',
    public: 'vwX/4yPfktiBVX2YZe23rtbyzd2XIDY0nLvjZaCBYno=',
  },
  {
    name: 'ttruong@bink.com',
    ip: '10.10.10.41',
    private: 'AIXHy9PDopg7AdF9V8NE0uAxPiU9oO1WwChG3pUjUWY=',
    public: 'h0EeHlUMIEjQ9+Awa0i6Oq736720k+VW5ASqrPxagkQ=',
  },
  {
    name: 'mrowe@bink.com',
    ip: '10.10.10.42',
    private: '2Fd2DMN05baVCYZyeNgmLo2cW3ir9JFh2Alx4Zwf83Y=',
    public: 'svzet6K67Qp7SxHbwnxh2k+h8CQQapneF2s0CZJg4nE=',
  },
  {
    name: 'nread@bink.com',
    ip: '10.10.10.45',
    private: 'ILZpBNzJVX4V1C/AybPv/ST3zxRUxPIKWTxcyj1du3M=',
    public: 'Nct4I3J9bBCdaKmsHjkk7afe/nqDW/KpzBOl7CWxkUo=',
  },
  {
    name: 'swilliams@bink.com',
    ip: '10.10.10.46',
    private: 'MJlLx3C+sUp4XJUtSFZrMOn691flchrpxgry+WqEOmM=',
    public: 'HI4Nj7C7Ge5T/kKhO1I07h6nL62FE5o5TUoTKLCQIxY=',
  },
  {
    name: 'sbransden@bink.com',
    ip: '10.10.10.48',
    private: 'KJIauRA5VU3ZRmypDrNqcsJEnr02XDqlfDAlGQV59Xo=',
    public: 'VNuj7O0SE18FTm/vvoV0TXwDMfGKJQwaVrUdaM8r2gA=',
  },
  {
    name: 'lKang@bink.com',
    ip: '10.10.10.53',
    private: '4E8ZZLtkPo8QYpiZttsxfDEm85EM3fvLyGR3AUjPAmE=',
    public: 'OdUjPl+94S3JNnr7b+TNxSX+t7XIVVYMVhhXi2m3sz8=',
  },
  {
    name: 'mjozwiak@bink.com',
    ip: '10.10.10.54',
    private: 'GF3Ka9OPammK2+xc/Fa7SP49OKjponaumdMNXbMpLno=',
    public: 'M2kWOmxtiLRGWRBwqMvzyp+kJ/IkVvR7FNuHHck7fTk=',
  },
  {
    name: 'jbest@bink.com',
    ip: '10.10.10.56',
    private: 'aCZ7Akto21fBtm83mH661UM3taAYBdzpvRcVSLUVHnI=',
    public: 'QwOKBE/j9D6kXAchQlnGTZ+zhINbYPgWyRmWIPq+G3A=',
  },
  {
    name: 'jwoodhams@bink.com',
    ip: '10.10.10.57',
    private: '2NLmVp6sFeZaPWidgqNBvt9TjcEROa4R3+2FO2TctHY=',
    public: 'ub5OLKRM4kdmyb4mJbb+NjzEbF4t/gE0mqDMTaSRLFk=',
  },
  {
    name: 'braghavan@bink.com',
    ip: '10.10.10.60',
    private: '0E9uXQyU3NG44XUk3zblf1n09BG1H7y8w5t7qRpdLH0=',
    public: 'kMSQsNac6RjwNh7cTj0fNnCEc/fEF1XwREIrHKiWNXQ=',
  },
  {
    name: 'jjones@bink.com',
    ip: '10.10.10.63',
    private: 'uNyS6xr3oaijBQwDXxqvhJD5qzkGjVOL4FRfs09SenU=',
    public: 'QMAU1cSZutMZY+RLvP2hr8RyTF9Md1mod7RhvTMZW3g=',
  },
  {
    name: 'lhamilton@bink.com',
    ip: '10.10.10.67',
    private: 'CKDjL2m5M6zay7eijaqeq5IRwJutZGXEmWB2qjHcYlk=',
    public: 'QHf2kkE2w2sR2Vh+Tt2RCBkcOThH6Rxu3w78e4NYtww=',
  },
  {
    name: 'kpatel@bink.com',
    ip: '10.10.10.68',
    private: 'ePJdUrnyAd+9RNdHbMCybDob0UDyO/JdKJzLZv/kTFw=',
    public: 'uNLtKMun8PlTXr4MJSjQRv4VgcCvua3NcbMX7SqHAlw=',
  },
  {
    name: 'cgouws@bink.com',
    ip: '10.10.10.69',
    private: 'wIq+uQnOEUgb9kqKIRiClcWs8lb0AdYIf5IAaAjKRlw=',
    public: 'sql1N10MXCEh7LPYf7bYBRzaNdQAiroM5P1QRTXNmhA=',
  },
  {
    name: 'lrowley@bink.com',
    ip: '10.10.10.70',
    private: '8Cpb/mZJQMK/ARAZRrREdeW/qOBaNxSqw6e6fAf5zlg=',
    public: '6YoMPLhtbqCKkPDZ3DPyXzxpeNM5iFMnf0pG9wultV4=',
  },
  {
    name: 'cmuntean@bink.com',
    ip: '10.10.10.71',
    private: '4LC10i7X2Qg4hQp8wr/moHXoijHKN4xZ7fLKrkG3g0I=',
    public: 'bpGj1NGwyyEOCaduLtXEfP5wkIPVEjSq0A+b2lNohFI=',
  },
  {
    name: 'hlantsbery@bink.com',
    ip: '10.10.10.72',
    private: 'gFzcH5J3GprnUO2/M9zepY+q34ytmn1mwMTSaYWMUEc=',
    public: 'UOJRDrhooa4EwhnhVgIU8yw4aZjD6ATuItKvuiM0eBA=',
  },
  {
    name: 'cmorrow@bink.com',
    ip: '10.10.10.73',
    private: 'gCBQZrAxquYhjwm5QgNVP4BNscbKLEWtPkn2yaPg1Ek=',
    public: 'VIREj8NM0+3FQkH/S3vS2W+5wZpV8DuSNeNCicjYpgQ=',
  },
  {
    name: 'hmazhar@bink.com',
    ip: '10.10.10.75',
    private: 'sGwNou1K55a2OkuKtjIsncdzUn8h/d4maeqvlywXvms=',
    public: '0qbhAb3laIEaJIkefd4d3KONYRw5quEsZD17EIaWEFE=',
  },
  {
    name: 'npatil@bink.com',
    ip: '10.10.10.77',
    private: 'CEXOHOMvDXhZjDLDIc6mRYzGGIg2OzG1vgD4DEkJ8GM=',
    public: 'FJPTlt7pEi7Z2CTWirWai4q8HWoW50zhenY9Ai0N1AE=',
  },
  {
    name: 'sgraham@bink.com',
    ip: '10.10.10.81',
    private: 'aE+4E6RRQH5m+H8N2bpjQdCCf9WQWFwSuUhjJs8urHo=',
    public: 'ylXdoYJ8chB8mOLWl+OwTBKe2YJ15CndlSwnSv5jQW8=',
  },
  {
    name: 'tviknarajah@bink.com',
    ip: '10.10.10.83',
    private: '+B3p9JUv1iZGUZP8lM+kDUsjHddrZh8QzDWMzMIwjlE=',
    public: 'OSuLRudaiGF6T+GPRMK3gmCBCTxbm1cRVGBp5vKRFxc=',
  },
  {
    name: 'bleadbitter@bink.com',
    ip: '10.10.10.84',
    private: 'CPmytzuFj8Ipuo2Nqvz5gmMhrJTNjDtPVNaBTMsXeXc=',
    public: 'fvW49JInRKbbC8rN0xaS+2pAKLYcvesnyJSAPkmSLD0=',
  },
  {
    name: 'rpatel@bink.com',
    ip: '10.10.10.85',
    private: '+Kxv1Jd+ISjQQOf4Oh1+zxTEkEcYGzLNLEFpu+d7MGI=',
    public: 'ZRZr8M85eyvfdS/XqfAkrBNgl+D47d1Z2/lO8JKdRV0=',
  },
  {
    name: 'jkurowski@bink.com',
    ip: '10.10.10.87',
    private: 'eEnIA+dTNjmEStkUa5yx4i5BJRRUEpD14Rbszqd4WUQ=',
    public: 'mvfjV0AHcFWgzZR/q6Sd7nD5tIQjlk+94WqhpMOLt0Q=',
  },
  {
    name: 'rsilva@bink.com',
    ip: '10.10.10.88',
    private: '0Ej94TLhOF0AP8kSgG8vEXKA22Frd3XBqjzwfCSLjV8=',
    public: 'YsESh4mbLSu2AbzyfBYVCW3aAAK87l5fvHWmqb2JqlI=',
  },
  {
    name: 'njames@bink.com',
    ip: '10.10.10.90',
    private: 'ICelfphZ/lIMBcPVZd531CSU6D+ycp0XI+lLz2Xlg0s=',
    public: 'l5RU8t3ph5nUZamlXtlt4Sc7EjpWcGJOcA4Cmv3y+3Q=',
  },
  {
    name: 'kkrastev@bink.com',
    ip: '10.10.10.91',
    private: 'CInRmbjWdDiAJXAXaqIn9d+iM7fzp2IIzOevK2gNwV0=',
    public: '9glb+YMiJPHs/CeFZ/S0+8kMCmBXyOsRnR4hz5H7MFI=',
  },
  {
    name: 'andrew_waddell',
    ip: '10.10.10.93',
    private: 'sGuzE53pOnQ1GaO4dZLkU0EkmSmuIXIhKAggVhk10X4=',
    public: 'UW3Ywf7af0Tk1ytN0tnyWZE29EppAwJWRRKrPsk7/Cw=',
  },
  {
    name: 'rfleming@bink.com',
    ip: '10.10.10.94',
    private: '+G6RB7JipVEtXrJU0BA1hDrwYlplHfQGYAruoJ7X8Vk=',
    public: 'x3a02ZkCuCMRTy1iAUkR+uFgLTv3ElAQUMiwBbjobDo=',
  },
  {
    name: 'jirving@bink.com',
    ip: '10.10.10.95',
    private: 'KITgBlvUVZF6kagE8KOo5xidRZRRdInx2Br0Iycm73o=',
    public: 'TXkKFinQeQuqQWMf1QZTKQWar2mpgMj20AVpky62+Cg=',
  },
  {
    name: 'ainnes@bink.com',
    ip: '10.10.10.96',
    private: 'MHq8GZD9e133a/F1F4in5kzb44cPOYu1hJp/mGXgD3c=',
    public: 'kq+AIEwJk2jAMUwHs5ikYcce03F4KgUna1L+i1MeuBA=',
  },
  {
    name: 'lcodrean@bink.com',
    ip: '10.10.10.97',
    private: 'APZo+oqM2g/p43FLXlHisS+7PJhj5lkR5sfAIjkv5XI=',
    public: 'A6T/3sGfnrlyKsP29VhwZXtuSptbO1KhP/UDdSPTIm8=',
  },
  {
    name: 'atierney@bink.com',
    ip: '10.10.10.98',
    private: 'mJbF9m0mELD4onloECvX96qyUHbY+GkmHG3Ug2MIjF4=',
    public: 'eitef2chXVldhzt0yWww3MVbwIw4gwSquO5xdVp35EI=',
  },
  {
    name: 'cmitchell@bink.com',
    ip: '10.10.10.99',
    private: 'KONB6a3XdffJtNajVULCqstLI20N/khPxfHfEocJIV8=',
    public: 'iSqEmH+sQrr6XKdyVHEKBUoNjUuH4yqCH70RSXEqkRk=',
  },
]
