---
- name: Install Wireguard
  apt:
    name: wireguard
    update_cache: true
    state: present
  
- name: Enable Wireguard
  systemd:
    name: wg-quick@wg0
    enabled: true
    daemon_reload: true

- name: Add ipforward in Wiregard Conf
  copy:
    dest: /etc/sysctl.d/99-wireguard.conf
    owner: root
    group: root
    content: |
      net.ipv4.ip_forward = 1
      net.ipv6.conf.all.forwarding=1
      net.ipv6.conf.default.forwarding=1
  register: ipforward

- name: Reload sysctl
  command: sysctl --system
  when: ipforward.changed == True

- name: Populate Wireguard Conf File
  template:
    src: wireguard.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0640'
  vars:
    server_private_key: '{{ wireguard_server_private_key }}'
    users: '{{ wireguard_users }}'
  notify: 
  - restart wireguard
  - restart automount

- name: Update cifs-utils
  apt:
    name: cifs-utils
    update_cache: true

- name: Create Mount Dir
  file:
    name: '{{ item }}'
    state: directory
  with_items:
    - /mnt/{{ storage_account_name }}
    - /mnt/{{ storage_account_name }}/users

- name: Install Azure Storage Mount
  template:
    src: storage.mount.j2
    dest: /etc/systemd/system/mnt-{{ storage_account_name }}-users.mount
    mode: '0644'

- name: Install Azure Storage Automount
  copy:
    src: storage.automount
    dest: /etc/systemd/system/mnt-{{ storage_account_name }}-users.automount
    mode: '0644'

- name: Enable automount Service
  systemd:
    name: mnt-{{ storage_account_name }}-users.automount
    daemon_reload: true
    enabled: true
    state: started

- name: Create Files for Each User
  template:
    src: users.conf.j2
    dest: /mnt/{{ storage_account_name }}/users/{{ item.name }}.conf
    owner: root
    group: root
    mode: '0644'
  vars:
    private: '{{ item.private }}'
    address: '{{ item.ip }}'
    srv_public: '{{ wireguard_server_public_key }}'
    srv_endpoint: '{{ wireguard_server_fqdn }}'
    srv_port: '{{ wireguard_server_port }}'
  loop: '{{ wireguard_users }}'


# Deactivate wireguard for users who have left
- name: Get List of Names on System
  find:
    paths: /mnt/{{ storage_account_name }}/users
    recurse: true
    file_type: any
  register: configs

- name: Convert Loop of Dict into List
  set_fact:
    system_names: "{{ system_names | default([]) + [ item | split('/') | last ] }}"
  loop: "{{ configs.files | map(attribute='path') }}"

- name: Get List of Names in Default
  set_fact:
    default_names: "{{ default_names | default([]) + [ item.name + '.conf' ]}}"
  loop: "{{ wireguard_users }}"

- name: Remove Files for Resigned Users
  file:
    path: /mnt/{{ storage_account_name }}/users/{{ item }}
    state: absent
  loop: "{{ system_names | difference(default_names) }}"
  notify: 
  - restart wireguard
  - restart automount
