---
## Set Up Postgres
- name: Add a Postgres Apt Key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add Postgres Repository
  apt_repository:
    filename: pgdg
    repo: deb https://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
    state: present

- name: Install Postgres Client 13
  apt:
    name: postgresql-client-13
    state: present
    update_cache: true

## Setup Postgres Driver
- name: Download Postgres Driver
  get_url:
    url: https://downloads.tableau.com/drivers/linux/postgresql/postgresql-42.3.3.jar
    dest: /home/{{ ansible_user }}/postgresql-42.3.3.jar

## Setup NGINX
- name: Add a NGINX Apt Key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add NGINX Apt Repo
  apt_repository:
    repo: deb https://nginx.org/packages/ubuntu {{ ansible_distribution_release }} nginx
    filename: nginx
    state: present

- name: Copy NGINX Preferences file
  copy:
    src: 99nginx
    dest: /etc/apt/preferences.d/99nginx
    mode: '0644'

- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Enable & Start NGINX
  systemd:
    name: nginx.service
    state: started
    enabled: true
    daemon_reload: true

## Setup Certbot
- name: Install Certbot
  community.general.snap:
    name: certbot
    classic: true

- name: Create Symbolic Link
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

## Setup Tableau
- name: Install Core Packages for Tableau
  apt:
    pkg:
      - fontconfig
      - net-tools
      - gdb
      - chrpath
      - freeglut3
      - libegl1-mesa
      - libxcomposite1
      - libxcursor1
      - libxi6
      - libxrandr2
      - libxrender1
      - libxtst6
      - lsb-core

- name: Download Tableau Packages
  get_url:
    url: https://downloads.tableau.com/esdalt/{{ tableau_version | replace('-', '.') }}/tableau-server-{{ tableau_version }}_amd64.deb
    dest: /home/{{ ansible_user }}/tableau-server-{{ tableau_version }}_amd64.deb

- name: Install Tableau
  apt: deb="/home/{{ ansible_user }}/tableau-server-{{ tableau_version }}_amd64.deb"

- name: Initialize TSM 
  shell: /opt/tableau/tableau_server/packages/scripts.*/initialize-tsm --accepteula

- name: Add User Tadmin
  user:
    name: tadmin
    groups: tableau,tsmadmin

- name: Source Tableau Server Scripts
  lineinfile:
    path: /root/.zshrc
    line: . /etc/profile.d/tableau_server.sh

- name: Move Postgres from Home Directory into Tableau
  copy:
    src: /home/{{ ansible_user }}/postgresql-42.3.3.jar
    dest: /opt/tableau/tableau_driver/jdbc/postgresql-42.3.3.jar
    remote_src: true

## Setup Simpleproxy
- name: Install Simple Proxy
  apt:
    name: simpleproxy
    state: present
    update_cache: true

- name: Add Simple Proxy Service File
  template:
    src: simpleproxy.service
    dest: /etc/systemd/system/simpleproxy.service
    mode: 0644

- name: Start Simple Proxy Service
  systemd:
    name: simpleproxy.service
    state: started
    daemon_reload: true
    enabled: true
