- name: Remove 'node_exporter' package
  apt:
    name: prometheus-node-exporter
    state: absent

- name: Create node exporter group
  group:
    name: node_exporter
    system: true
    state: present

- name: Create node_exporter user
  user:
    name: node_exporter
    system: true
    groups: node_exporter
    shell: /usr/sbin/nologi

- name: Create node_exporter dir
  file:
    path: /opt/node_exporter
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: copy node_exporter file
  get_url:
    url: "{{ node_exporter_url }}"
    dest: /opt/node_exporter/{{ node_exporter_version }}
    owner: root
    group: root
    mode: '0755'
    checksum: sha256:{{ node_exporter_checksum }}

# - name: create node_exporter file in sbin
#   file:
#     path: /usr/local/sbin/node_exporter
#     state: touch

- name: Create symbolic link for node_exporter
  file:
    src: /opt/node_exporter/{{ node_exporter_version }}
    dest: /usr/local/sbin/node_exporter
    state: link

- name: Add node_exporter service file
  template: src=node_exporter.service dest=/etc/systemd/system/node_exporter.service mode=0644

- name: start node_exporter service
  service:
    name: node_exporter.service
    state: started
    enabled: yes
    daemon_reload: yes
