---
- name: Remove 'node_exporter' Package
  apt:
    name: prometheus-node-exporter
    state: absent

- name: Create Node Exporter Group
  group:
    name: node_exporter
    system: true
    state: present

- name: Create Node Exporter User
  user:
    name: node_exporter
    system: true
    groups: node_exporter
    shell: /usr/sbin/nologin

- name: Create Node Exporter Directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /opt/node_exporter
    - /opt/node_exporter/{{ node_exporter_version }}

- name: Download Node Exporter
  ansible.builtin.unarchive:
    src: '{{ node_exporter_url }}'
    dest: /opt/node_exporter/{{ node_exporter_version }}
    extra_opts:
      - --strip=1
    owner: root
    group: root
    remote_src: yes

- name: Create Symbolic Link for Node Exporter
  file:
    src: /opt/node_exporter/{{ node_exporter_version }}/node_exporter
    dest: /usr/local/sbin/node_exporter
    state: link

- name: Add Node Exporter Service File
  template:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644

- name: start Node Exporter Service
  systemd:
    name: node_exporter.service
    state: started
    daemon_reload: true
    enabled: true
