---
- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: true
    update_cache: true
  retries: 3

- name: Add core packages
  become: true
  apt:
    pkg:
      - apt-transport-https
      - software-properties-common
      - curl
      - htop
      - dstat
      - screen
      - zsh
      - tcpdump
      - nano
      - vim
      - openssh-server
      - openssh-client
      - libpam-google-authenticator
