- name: Create .ara directory
  file:
    path: /home/{{ ansible_user }}/.ara
    state: directory
    mode: '0755'

- name: Create .ara/server directory
  file:
    path: /home/{{ ansible_user }}/.ara/server
    state: directory
    mode: '0755'

- name: Add settings.yaml with Whitelisted URL
  copy:
    src: settings.yaml
    dest: /home/{{ ansible_user }}/.ara/server/settings.yaml
    owner: root
    group: root
    mode: '0770'
  register: settings

- name: Pull ARA Docker image
  community.docker.docker_image:
    name: docker.io/recordsansible/ara-api:latest
    source: pull

- name: Create ARA containers
  community.docker.docker_container:
    name: ara-api-server
    image: docker.io/recordsansible/ara-api:latest
    state: started
    restart: yes
    detach: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - /home/{{ ansible_user }}/.ara/server:/opt/ara:z
  when: settings.changed
