---
- name: Install Wireguard
  apt:
    name: wireguard
    update_cache: true
    state: present
  
- name: enable wireguard
  systemd:
    name: wg-quick@wg0
    enabled: true
    daemon_reload: true

- name: Add ipforward in Wiregard Conf
  copy:
    dest: /etc/sysctl.d/99-wireguard.conf
    owner: root
    group: root
    content: |
      net.ipv4.ip_forward = 1
  register: ipforward

- name: Reload sysctl
  command: sysctl --system
  when: ipforward.changed == True

- name: Populate Wireguard Conf File
  template:
    src: wireguard.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: '0640'
  vars:
    server_private_key: '{{ wireguard_server_private_key }}'
    users: '{{ wireguard_users }}'
  notify: 
  - restart wireguard
  - restart automount

- name: Update cifs-utils
  apt:
    name: cifs-utils
    update_cache: true

- name: Create Mount Dir
  file:
    name: '{{ item }}'
    state: directory
  with_items:
    - /mnt/binkuksouthwireguard
    - /mnt/binkuksouthwireguard/users

- name: Install Mount Service Scripts
  copy:
    src: '{{ item }}'
    dest: /etc/systemd/system/{{ item }}
    mode: '0644'
  with_items:
    - mnt-binkuksouthwireguard-users.mount
    - mnt-binkuksouthwireguard-users.automount

- name: Enable automount Service
  systemd:
    name: mnt-binkuksouthwireguard-users.automount
    daemon_reload: true
    enabled: true
    state: started

- name: Create Files for Each User
  template:
    src: users.conf.j2
    dest: /mnt/binkuksouthwireguard/users/{{ item.name }}.conf
    owner: root
    group: root
    mode: '0644'
  vars:
    private: '{{ item.private }}'
    address: '{{ item.ip }}'
    srv_public: '{{ wireguard_server_public_key }}'
    srv_endpoint: '{{ wireguard_server_fqdn }}'
    srv_port: '{{ wireguard_server_port }}'
  loop: '{{ wireguard_users }}'
